### PR TITLE
rss_client: fix syntax error

### PR DESCRIPTION
**Pull request by yanan-fu**
Issue:https://github.com/avocado-framework/aexpect/issues/94

Signed-off-by: Yanan Fu <yfu@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
@ldoktor  I found this issue was introduced by https://github.com/avocado-framework/aexpect/pull/87,  could you help review ?
Thanks!

**Review by luckyh — APPROVED** [review]

**Review by ldoktor — APPROVED** [review]
Thanks for fixing this typo

**Comment by ldoktor** [comment]
@yanan-fu would you need us to push a new version to pip or are you following the master so it'd be possible for us to wait for more fixes to accumulate?

**Comment by yanan-fu** [comment]
> @yanan-fu would you need us to push a new version to pip or are you following the master so it'd be possible for us to wait for more fixes to accumulate?

@ldoktor  Master is ok for our testing, you can push new version to pip as your schedule, thanks for asking !

**Pull request merged**
