### PR TITLE
Makefile: add a pypi target to ease future releases

### PR DESCRIPTION
**Pull request by clebergnu**
Signed-off-by: Cleber Rosa <crosa@redhat.com>

### CODE REVIEW

**Review by pevogam — COMMENTED** [review]
How about fully automating the upload? This is how we do it for the Avocado I2N plugin:

https://github.com/intra2net/avocado-i2n/blob/e12349ebb0b5810edc1020aeeb748a6f0d0e2bf2/.travis.yml#L62

**Review by ldoktor — COMMENTED** [review]
Would you please add the PYPI_UPLOAD dir to the cleanup? Also depends whether you want to use @pevogam's automation suggestion...

**Comment by lmr** [comment]
That automation looks nice. I'll take a look at it as well.

**Comment by lmr** [comment]
Merged, thanks @clebergnu !

**Comment by pevogam** [comment]
@lmr This PR needed to add the `PYPI_UPLOAD` dir to the cleanup as @ldoktor suggested or to consider an even easier approach first. I guess we were in a hurry to automate it or something, not sure.

**Pull request merged**
